GameTypes = ['独立', '动作', '冒险', '休闲', '模拟', '策略', '角色扮演', '抢先体验', '免费', '单人', '暴力', '体育', '大型多人在线', '血腥', '竞速',
             '裸露', '好评原声音轨', '氛围', '二维', '色情内容', '解谜', '多人', '剧情丰富', '困难', '动漫', '奇幻', '虚拟现实', '恐怖', '欢乐',
             '像素图形', '科幻', '射击', '第一人称视角', '女性主角', '开放世界', '平台游戏', '合作', '实用工具', '阖家', '怀旧', '生存', '街机',
             '第一人称射击', '回合制', '设计与插画', '喜剧', '可爱', '视觉小说', '探索', '沙盒', '重玩价值', '在线合作', '放松', '电影', '经典',
             '心理恐怖', '大师级', '指向 & 点击', '控制器', '彩色', '第三人称视角', '太空', '快节奏', '本地多人', '战术', '教育', '黑暗', '僵尸',
             '成人', '物理', '悬疑', '网红', '拟真', '动画制作和建模', '短片', '建造', '软件', '管理', '音频制作', '生存恐怖', '网络出版', '清版射击',
             '动作冒险', '本地合作', '团队角色扮演', '选择取向', '横向滚屏', '类Rogue', 'RPG制作大师', '战争', '动作角色扮演', '制作', '步行模拟', '历史',
             '纵轴', '竞技', '平台解谜', '回合战略', '音乐', '轻度 Rogue', '即时战略', '玩家对战', '视频制作', '弹幕射击', '日系角色扮演', '黑暗奇幻',
             '角色定制', '极简主义', '唯美', '隐藏物体', '格斗', '砍杀', '末日', '复古', '恋爱模拟', '潜行', '程序生成', '欲罢不能', '爱情', '未来',
             '卡通化', '风格化', '多结局', '第三人称射击', '中世纪', '迷宫探索', '剧情', '基地建设', '塔防', '4人本地', '可模组化', '回合制战斗', '军事',
             '资源管理', '超现实', '魔法', '卡牌游戏', '垂直卷轴射击', '赛博朋克', '黑色幽默', '二战', '机器人', '等角', '经济', '团队导向', '剧集',
             '鲜血', '试验性', '3D', '原声音乐', '驾驶', '手绘', '清版动作', '大型多人在线角色扮演', '城市营造', '软件培训', '回合制战术', '3D 平台',
             '类银河战士恶魔城', '惊悚', '自选历险体验', 'Epic', '互动小说', '光明会', '游戏开发', '卡通', '永久死亡', 'LGBTQ+', '桌游', '外星人',
             '非主流经典', '推理', '双摇杆射击', '文字为基础', '飞行', '毁灭', '动作类 Rogue', '竞技场射击', '犯罪', '跑酷', 'Hentai', '心理',
             '仅鼠标', '寻宝', 'PvE', '关卡编辑', '90 年代', '即时', '逻辑', '伪3D', '抽象', '汽车模拟', '黑色喜剧', '80 年代', '大战略',
             '恶魔', '反乌托邦', '洛夫克拉夫特式', '架空', '工作场所不宜', '三消', '即时含暂停', 'Kickstarter', '轻游戏', '照片编辑', '分屏',
             '蒸汽朋克', '节奏', '多人在线战术竞技', '太空模拟', '2D 格斗', '竞分', '战争游戏', '单线剧情', '策略角色扮演', '游戏制作', '即时战术',
             '战术角色扮演', '科学', '纪录片', '机甲世界', '火车', '大逃杀', '坦克', '记叙', '故事架构丰富', '触控', '政治性', '迷幻', '时间管理', '重制',
             '类魂系列', '情感', '模组', '4X', '合作战役', '3D视觉', '龙', '剑术', '电竞', '海盗', '体验', '奔跑', '角色动作', '冷战', '忍者',
             '体素', '少女游戏', '灵异', '恐龙', '政治', '龙与地下城', '教程', '漫画', '超級英雄', '2D 平台', '物品管理', '电脑角色扮演', '游戏工坊',
             '黑客', '海军', '交易卡牌', '现代', '过场动画', '自制枪械', '讽刺', '创世神', '众筹', '自然', '黑色', '六角格棋盘', '西部', '谐仿',
             '非线性', '开放世界生存制作', '哲理', '无声主角', '网格导向动作', '小游戏', '暗杀', '农业', 'TrackIR', '子弹时间', '猫', '时空旅行',
             '神话', '游戏相关', '哥特', '限时', '恶人主角', '狩猎', '美国', '牌组构建', '狗', '水底', '全动态影像', '职业导向', '足球/美式足球',
             '桌上游戏', '劫掠', '贸易', '武术', '卡牌战斗', '快速反应事件', '钓鱼', '足球', '吸血鬼', '一战', '推理调查', '唯美格斗', '编程', '时空操控',
             '小说改编', '殖民模拟', '文字游戏', '采矿', '阴谋', '资本主义', '狙击手', '沉浸式模拟', '人工智能', '异步多人', '农场模拟', '续作',
             '不可思议迷宫', '音乐动态生成', '信仰', '海战', '动态记叙', '360 视频', '棋类', '马匹', '越野', '战锤40K', '帆船', '政治模拟', '乐高',
             '低容错', '精确平台', '六自由度', '外交', '弹球', '火星', '星球大战', '赌博', '益智问答', '交谈', '轨道射击', '打字', '战斗', '推箱子',
             '生活模拟', '地底', '罗马', 'Steam 主机', '蓄意操控困难', '狼人', '高尔夫球', '传统类 Rogue', '摩托车', '纸牌', '自动化', '标杆测试',
             '篮球', '蝙蝠侠', '车辆作战', '迷你高尔夫', '超人类主义', '单车', '硬件', '3D 格斗', '战斗竞速', '懒人游戏', '长片电影', '拳击', '摔角',
             '潜水艇', '英雄射击', '医疗模拟', '交通运输', '雪', '射箭', '外国', '棒球', '台球', '骑车', '刷宝射击游戏', '网球', '保龄球', '非对称 VR',
             '喷气机', '滑板', 'Rogue 恶魔城', '冰球', '劳拉·克劳馥', '声控', '摩托车越野', '收集马拉松', '旅鼠', '拼字', '疫病爆发模拟', '滑行',
             '情境', '社交推理', '单板滑雪', '滑雪', '自行车越野', '电子音乐', '自走棋', '器乐', 'ATV', '电子', '摇滚乐']

TypeUrls = {
    '独立': 'https://store.steampowered.com/search/?&tags=492&snr=1_241_4_indie',
    '动作': 'https://store.steampowered.com/search/?&tags=19&snr=1_241_4_action',
    '冒险': 'https://store.steampowered.com/search/?&tags=21&snr=1_241_4_adventure',
    '休闲': 'https://store.steampowered.com/search/?&tags=597&snr=1_241_4_casual',
    '模拟': 'https://store.steampowered.com/search/?&tags=599&snr=1_241_4_simulation',
    '策略': 'https://store.steampowered.com/search/?&tags=9&snr=1_241_4_strategy',
    '角色扮演': 'https://store.steampowered.com/search/?&tags=122&snr=1_241_4_rpg',
    '抢先体验': 'https://store.steampowered.com/search/?&genre=Early%20Access&snr=1_1520_4_',
    '免费': 'https://store.steampowered.com/search/?&genre=Free%20to%20Play&snr=1_1510_4_',
    '单人': 'https://store.steampowered.com/search/?&tags=4182&snr=1_241_4_singleplayer',
    '暴力': 'https://store.steampowered.com/search/?&tags=4667&snr=1_241_4_violent',
    '体育': 'https://store.steampowered.com/search/?&tags=701&snr=1_241_4_sports',
    '大型多人在线': 'https://store.steampowered.com/search/?&tags=128&snr=1_241_4_massivelymultiplayer',
    '血腥': 'https://store.steampowered.com/search/?&tags=4345&snr=1_241_4_gore',
    '竞速': 'https://store.steampowered.com/search/?&tags=699&snr=1_241_4_racing',
    '裸露': 'https://store.steampowered.com/search/?&tags=6650&snr=1_241_4_nudity',
    '好评原声音轨': 'https://store.steampowered.com/search/?&tags=1756&snr=1_241_4_greatsoundtrack',
    '氛围': 'https://store.steampowered.com/search/?&tags=4166&snr=1_241_4_atmospheric',
    '二维': 'https://store.steampowered.com/search/?&tags=3871&snr=1_241_4_d',
    '色情内容': 'https://store.steampowered.com/search/?&tags=12095&snr=1_241_4_sexualcontent',
    '解谜': 'https://store.steampowered.com/search/?&tags=1664&snr=1_241_4_puzzle',
    '多人': 'https://store.steampowered.com/search/?&tags=3859&snr=1_241_4_multiplayer',
    '剧情丰富': 'https://store.steampowered.com/search/?&tags=1742&snr=1_241_4_storyrich',
    '困难': 'https://store.steampowered.com/search/?&tags=4026&snr=1_241_4_difficult',
    '动漫': 'https://store.steampowered.com/search/?&tags=4085&snr=1_241_4_anime',
    '奇幻': 'https://store.steampowered.com/search/?&tags=1684&snr=1_241_4_fantasy',
    '虚拟现实': 'https://store.steampowered.com/search/?&vrsupport=402&snr=1_1453_4_',
    '恐怖': 'https://store.steampowered.com/search/?&tags=1667&snr=1_241_4_horror',
    '欢乐': 'https://store.steampowered.com/search/?&tags=4136&snr=1_241_4_funny',
    '像素图形': 'https://store.steampowered.com/search/?&tags=3964&snr=1_241_4_pixelgraphics',
    '科幻': 'https://store.steampowered.com/search/?&tags=3942&snr=1_241_4_scifi',
    '射击': 'https://store.steampowered.com/search/?&tags=1774&snr=1_241_4_shooter',
    '第一人称视角': 'https://store.steampowered.com/search/?&tags=3839&snr=1_241_4_firstperson',
    '女性主角': 'https://store.steampowered.com/search/?&tags=7208&snr=1_241_4_femaleprotagonist',
    '开放世界': 'https://store.steampowered.com/search/?&tags=1695&snr=1_241_4_openworld',
    '平台游戏': 'https://store.steampowered.com/search/?&tags=1625&snr=1_241_4_platformer',
    '合作': 'https://store.steampowered.com/search/?&tags=1685&snr=1_241_4_coop',
    '实用工具': 'https://store.steampowered.com/search/?&tags=87&snr=1_241_4_utilities',
    '阖家': 'https://store.steampowered.com/search/?&tags=5350&snr=1_241_4_familyfriendly',
    '怀旧': 'https://store.steampowered.com/search/?&tags=4004&snr=1_241_4_retro',
    '生存': 'https://store.steampowered.com/search/?&tags=1662&snr=1_241_4_survival',
    '街机': 'https://store.steampowered.com/search/?&tags=1773&snr=1_241_4_arcade',
    '第一人称射击': 'https://store.steampowered.com/search/?&tags=1663&snr=1_241_4_fps',
    '回合制': 'https://store.steampowered.com/search/?&tags=1677&snr=1_241_4_turnbased',
    '设计与插画': 'https://store.steampowered.com/search/?&tags=84&snr=1_241_4_designillustration',
    '喜剧': 'https://store.steampowered.com/search/?&tags=1719&snr=1_241_4_comedy',
    '可爱': 'https://store.steampowered.com/search/?&tags=4726&snr=1_241_4_cute',
    '视觉小说': 'https://store.steampowered.com/search/?&tags=3799&snr=1_241_4_visualnovel',
    '探索': 'https://store.steampowered.com/search/?&tags=3834&snr=1_241_4_exploration',
    '沙盒': 'https://store.steampowered.com/search/?&tags=3810&snr=1_241_4_sandbox',
    '重玩价值': 'https://store.steampowered.com/search/?&tags=4711&snr=1_241_4_replayvalue',
    '在线合作': 'https://store.steampowered.com/search/?&tags=3843&snr=1_241_4_onlinecoop',
    '放松': 'https://store.steampowered.com/search/?&tags=1654&snr=1_241_4_relaxing',
    '电影': None,
    '经典': 'https://store.steampowered.com/search/?&tags=1693&snr=1_241_4_classic',
    '心理恐怖': 'https://store.steampowered.com/search/?&tags=1721&snr=1_241_4_psychologicalhorror',
    '大师级': 'https://store.steampowered.com/search/?&tags=5144&snr=1_241_4_masterpiece',
    '指向 & 点击': 'https://store.steampowered.com/search/?&tags=1698&snr=1_241_4_pointclick',
    '控制器': 'https://store.steampowered.com/search/?&tags=7481&snr=1_241_4_1500',
    '彩色': 'https://store.steampowered.com/search/?&tags=4305&snr=1_241_4_colorful',
    '第三人称视角': 'https://store.steampowered.com/search/?&tags=1697&snr=1_241_4_thirdperson',
    '太空': 'https://store.steampowered.com/search/?&tags=1755&snr=1_241_4_space',
    '快节奏': 'https://store.steampowered.com/search/?&tags=1734&snr=1_241_4_fastpaced',
    '本地多人': 'https://store.steampowered.com/search/?&tags=7368&snr=1_241_4_localmultiplayer',
    '战术': 'https://store.steampowered.com/search/?&tags=1708&snr=1_241_4_tactical',
    '教育': 'https://store.steampowered.com/search/?&tags=1036&snr=1_241_4_education',
    '黑暗': 'https://store.steampowered.com/search/?&tags=4342&snr=1_241_4_dark',
    '僵尸': 'https://store.steampowered.com/search/?&tags=1659&snr=1_241_4_zombies',
    '成人': 'https://store.steampowered.com/search/?&tags=5611&snr=1_241_4_mature',
    '物理': 'https://store.steampowered.com/search/?&tags=3968&snr=1_241_4_physics',
    '悬疑': 'https://store.steampowered.com/search/?&tags=5716&snr=1_241_4_mystery',
    '网红': 'https://store.steampowered.com/search/?&tags=10397&snr=1_241_4_memes',
    '拟真': 'https://store.steampowered.com/search/?&tags=4175&snr=1_241_4_realistic',
    '动画制作和建模': 'https://store.steampowered.com/search/?&tags=872&snr=1_241_4_animationmodeling',
    '短片': 'https://store.steampowered.com/search/?&tags=4234&snr=1_241_4_short',
    '建造': 'https://store.steampowered.com/search/?&tags=1643&snr=1_241_4_building',
    '软件': 'https://store.steampowered.com/search/?&category1=994,996&snr=1_1451_4_',
    '管理': 'https://store.steampowered.com/search/?&tags=12472&snr=1_241_4_management',
    '音频制作': None,
    '生存恐怖': 'https://store.steampowered.com/search/?&tags=3978&snr=1_241_4_survivalhorror',
    '网络出版': 'https://store.steampowered.com/search/?&tags=1038&snr=1_241_4_webpublishing',
    '清版射击': None,
    '动作冒险': 'https://store.steampowered.com/search/?&tags=4106&snr=1_241_4_actionadventure',
    '本地合作': 'https://store.steampowered.com/search/?&tags=3841&snr=1_241_4_localcoop',
    '团队角色扮演': 'https://store.steampowered.com/search/?&tags=10695&snr=1_241_4_partybasedrpg',
    '选择取向': 'https://store.steampowered.com/search/?&tags=6426&snr=1_241_4_choicesmatter',
    '横向滚屏': 'https://store.steampowered.com/search/?&tags=3798&snr=1_241_4_sidescroller',
    '类Rogue': 'https://store.steampowered.com/search/?&tags=1716&snr=1_241_4_roguelike',
    'RPG制作大师': 'https://store.steampowered.com/search/?&tags=5577&snr=1_241_4_rpgmaker',
    '战争': 'https://store.steampowered.com/search/?&tags=1678&snr=1_241_4_war',
    '动作角色扮演': 'https://store.steampowered.com/search/?&tags=4231&snr=1_241_4_actionrpg',
    '制作': 'https://store.steampowered.com/search/?&tags=1702&snr=1_241_4_crafting',
    '步行模拟': 'https://store.steampowered.com/search/?&tags=5900&snr=1_241_4_walkingsimulator',
    '历史': 'https://store.steampowered.com/search/?&tags=3987&snr=1_241_4_historical',
    '纵轴': 'https://store.steampowered.com/search/?&tags=4791&snr=1_241_4_topdown',
    '竞技': 'https://store.steampowered.com/search/?&tags=3878&snr=1_241_4_competitive',
    '平台解谜': 'https://store.steampowered.com/search/?&tags=5537&snr=1_241_4_puzzleplatformer',
    '回合战略': 'https://store.steampowered.com/search/?&tags=1741&snr=1_241_4_turnbasedstrategy',
    '音乐': 'https://store.steampowered.com/search/?&tags=1621&snr=1_241_4_music',
    '轻度 Rogue': 'https://store.steampowered.com/search/?&tags=3959&snr=1_241_4_roguelite',
    '即时战略': 'https://store.steampowered.com/search/?&tags=1676&snr=1_241_4_rts',
    '玩家对战': 'https://store.steampowered.com/search/?&tags=1775&snr=1_241_4_pvp',
    '视频制作': 'https://store.steampowered.com/search/?&tags=784&snr=1_241_4_videoproduction',
    '弹幕射击': 'https://store.steampowered.com/search/?&tags=4885&snr=1_241_4_bullethell',
    '日系角色扮演': 'https://store.steampowered.com/search/?&tags=4434&snr=1_241_4_jrpg',
    '黑暗奇幻': 'https://store.steampowered.com/search/?&tags=4604&snr=1_241_4_darkfantasy',
    '角色定制': 'https://store.steampowered.com/search/?&tags=4747&snr=1_241_4_charactercustomization',
    '极简主义': None,
    '唯美': 'https://store.steampowered.com/search/?&tags=5411&snr=1_241_4_beautiful',
    '隐藏物体': None,
    '格斗': 'https://store.steampowered.com/search/?&tags=1743&snr=1_241_4_fighting',
    '砍杀': 'https://store.steampowered.com/search/?&tags=1646&snr=1_241_4_hackandslash',
    '复古': 'https://store.steampowered.com/search/?&tags=3916&snr=1_241_4_oldschool',
    '恋爱模拟': 'https://store.steampowered.com/search/?&tags=9551&snr=1_241_4_datingsim',
    '潜行': 'https://store.steampowered.com/search/?&tags=1687&snr=1_241_4_stealth',
    '欲罢不能': 'https://store.steampowered.com/search/?&tags=4190&snr=1_241_4_addictive',
    '爱情': 'https://store.steampowered.com/search/?&tags=4947&snr=1_241_4_romance',
    '未来': 'https://store.steampowered.com/search/?&tags=4295&snr=1_241_4_futuristic',
    '卡通化': 'https://store.steampowered.com/search/?&tags=4195&snr=1_241_4_cartoony',
    '风格化': None,
    '多结局': 'https://store.steampowered.com/search/?&tags=6971&snr=1_241_4_multipleendings',
    '第三人称射击': 'https://store.steampowered.com/search/?&tags=3814&snr=1_241_4_thirdpersonshooter',
    '中世纪': 'https://store.steampowered.com/search/?&tags=4172&snr=1_241_4_medieval',
    '迷宫探索': 'https://store.steampowered.com/search/?&tags=1720&snr=1_241_4_dungeoncrawler',
    '剧情': 'https://store.steampowered.com/search/?&tags=5984&snr=1_241_4_drama',
    '基地建设': 'https://store.steampowered.com/search/?&tags=7332&snr=1_241_4_basebuilding',
    '塔防': 'https://store.steampowered.com/search/?&tags=1645&snr=1_241_4_towerdefense',
    '4人本地': 'https://store.steampowered.com/search/?&tags=4840&snr=1_241_4_playerlocal',
    '可模组化': 'https://store.steampowered.com/search/?&tags=1669&snr=1_241_4_moddable',
    '回合制战斗': 'https://store.steampowered.com/search/?&tags=4325&snr=1_241_4_turnbasedcombat',
    '军事': 'https://store.steampowered.com/search/?&tags=4168&snr=1_241_4_military',
    '资源管理': 'https://store.steampowered.com/search/?&tags=8945&snr=1_241_4_resourcemanagement',
    '超现实': 'https://store.steampowered.com/search/?&tags=1710&snr=1_241_4_surreal',
    '魔法': 'https://store.steampowered.com/search/?&tags=4057&snr=1_241_4_magic',
    '卡牌游戏': 'https://store.steampowered.com/search/?&tags=1666&snr=1_241_4_cardgame',
    '垂直卷轴射击': 'https://store.steampowered.com/search/?&tags=4637&snr=1_241_4_topdownshooter',
    '赛博朋克': 'https://store.steampowered.com/search/?&tags=4115&snr=1_241_4_cyberpunk',
    '黑色幽默': 'https://store.steampowered.com/search/?&tags=5923&snr=1_241_4_darkhumor',
    '二战': 'https://store.steampowered.com/search/?&tags=4150&snr=1_241_4_worldwarii',
    '机器人': 'https://store.steampowered.com/search/?&tags=5752&snr=1_241_4_robots',
    '等角': 'https://store.steampowered.com/search/?&tags=5851&snr=1_241_4_isometric',
    '经济': 'https://store.steampowered.com/search/?&tags=4695&snr=1_241_4_economy',
    '剧集': 'https://store.steampowered.com/search/?&tags=4242&snr=1_241_4_episodic',
    '鲜血': 'https://store.steampowered.com/search/?&tags=5228&snr=1_241_4_blood',
    '试验性': None,
    '3D': None,
    '原声音乐': None,
    '驾驶': 'https://store.steampowered.com/search/?&tags=1644&snr=1_241_4_driving',
    '手绘': 'https://store.steampowered.com/search/?&tags=6815&snr=1_241_4_handdrawn',
    '清版动作': 'https://store.steampowered.com/search/?&tags=4158&snr=1_241_4_beatemup',
    '大型多人在线角色扮演': 'https://store.steampowered.com/search/?&tags=1754&snr=1_241_4_mmorpg',
    '城市营造': 'https://store.steampowered.com/search/?&tags=4328&snr=1_241_4_citybuilder',
    '软件培训': None,
    '回合制战术': 'https://store.steampowered.com/search/?&tags=14139&snr=1_241_4_turnbasedtactics',
    '3D 平台': 'https://store.steampowered.com/search/?&tags=5395&snr=1_241_4_dplatformer',
    '类银河战士恶魔城': 'https://store.steampowered.com/search/?&tags=1628&snr=1_241_4_metroidvania',
    '惊悚': None,
    '自选历险体验': 'https://store.steampowered.com/search/?&tags=4486&snr=1_241_4_chooseyourownadventure',
    'Epic': None,
    '互动小说': None,
    '光明会': None,
    '游戏开发': 'https://store.steampowered.com/search/?&tags=13906&snr=1_241_4_gamedevelopment',
    '卡通': 'https://store.steampowered.com/search/?&tags=4562&snr=1_241_4_cartoon',
    '永久死亡': 'https://store.steampowered.com/search/?&tags=1759&snr=1_241_4_permadeath',
    'LGBTQ+': 'https://store.steampowered.com/search/?&tags=44868&snr=1_241_4_lgbtq',
    '桌游': 'https://store.steampowered.com/search/?&tags=1770&snr=1_241_4_boardgame',
    '外星人': 'https://store.steampowered.com/search/?&tags=1673&snr=1_241_4_aliens',
    '非主流经典': 'https://store.steampowered.com/search/?&tags=7782&snr=1_241_4_cultclassic',
    '推理': 'https://store.steampowered.com/search/?&tags=5613&snr=1_241_4_detective',
    '双摇杆射击': None,
    '文字为基础': None,
    '飞行': 'https://store.steampowered.com/search/?&tags=15045&snr=1_241_4_flight',
    '毁灭': 'https://store.steampowered.com/search/?&tags=5363&snr=1_241_4_destruction',
    '动作类 Rogue': 'https://store.steampowered.com/search/?&tags=42804&snr=1_241_4_actionroguelike',
    '竞技场射击': 'https://store.steampowered.com/search/?&tags=5547&snr=1_241_4_arenashooter',
    '犯罪': 'https://store.steampowered.com/search/?&tags=6378&snr=1_241_4_crime',
    '跑酷': 'https://store.steampowered.com/search/?&tags=4036&snr=1_241_4_parkour',
    'Hentai': None,
    '心理': 'https://store.steampowered.com/search/?&tags=5186&snr=1_241_4_psychological',
    '仅鼠标': None, '寻宝': 'https://store.steampowered.com/search/?&tags=4236&snr=1_241_4_loot',
    'PvE': 'https://store.steampowered.com/search/?&tags=6730&snr=1_241_4_pve',
    '关卡编辑': 'https://store.steampowered.com/search/?&tags=8122&snr=1_241_4_leveleditor',
    '90 年代': 'https://store.steampowered.com/search/?&tags=6691&snr=1_241_4_s',
    '即时': 'https://store.steampowered.com/search/?&tags=4161&snr=1_241_4_realtime',
    '逻辑': None,
    '伪3D': 'https://store.steampowered.com/search/?&tags=4975&snr=1_241_4_d',
    '抽象': None,
    '汽车模拟': 'https://store.steampowered.com/search/?&tags=1100687&snr=1_241_4_automobilesim',
    '黑色喜剧': None,
    '80 年代': None,
    '大战略': 'https://store.steampowered.com/search/?&tags=4364&snr=1_241_4_grandstrategy',
    '恶魔': 'https://store.steampowered.com/search/?&tags=9541&snr=1_241_4_demons',
    '反乌托邦': 'https://store.steampowered.com/search/?&tags=5030&snr=1_241_4_dystopian',
    '洛夫克拉夫特式': 'https://store.steampowered.com/search/?&tags=7432&snr=1_241_4_lovecraftian',
    '架空': 'https://store.steampowered.com/search/?&tags=4598&snr=1_241_4_alternatehistory',
    '工作场所不宜': None,
    '三消': None,
    '即时含暂停': 'https://store.steampowered.com/search/?&tags=7107&snr=1_241_4_realtimewithpause',
    'Kickstarter': 'https://store.steampowered.com/search/?&tags=5153&snr=1_241_4_kickstarter',
    '轻游戏': 'https://store.steampowered.com/search/?&tags=379975&snr=1_241_4_clicker',
    '照片编辑': None,
    '分屏': 'https://store.steampowered.com/search/?&tags=10816&snr=1_241_4_splitscreen',
    '蒸汽朋克': 'https://store.steampowered.com/search/?&tags=1777&snr=1_241_4_steampunk',
    '节奏': 'https://store.steampowered.com/search/?&tags=1752&snr=1_241_4_rhythm',
    '多人在线战术竞技': None,
    '太空模拟': 'https://store.steampowered.com/search/?&tags=16598&snr=1_241_4_spacesim',
    '2D 格斗': 'https://store.steampowered.com/search/?&tags=4736&snr=1_241_4_dfighter',
    '竞分': None, '战争游戏': 'https://store.steampowered.com/search/?&tags=4684&snr=1_241_4_wargame',
    '单线剧情': None,
    '策略角色扮演': 'https://store.steampowered.com/search/?&tags=17305&snr=1_241_4_strategyrpg',
    '游戏制作': 'https://store.steampowered.com/search/?&tags=1649&snr=1_241_4_gamemaker',
    '即时战术': 'https://store.steampowered.com/search/?&tags=3813&snr=1_241_4_realtimetactics',
    '战术角色扮演': 'https://store.steampowered.com/search/?&tags=21725&snr=1_241_4_tacticalrpg',
    '科学': 'https://store.steampowered.com/search/?&tags=5794&snr=1_241_4_science',
    '纪录片': None,
    '机甲世界': 'https://store.steampowered.com/search/?&tags=4821&snr=1_241_4_mechs',
    '火车': 'https://store.steampowered.com/search/?&tags=1616&snr=1_241_4_trains',
    '大逃杀': 'https://store.steampowered.com/search/?&tags=176981&snr=1_241_4_battleroyale',
    '坦克': 'https://store.steampowered.com/search/?&tags=13276&snr=1_241_4_tanks', '记叙': None,
    '故事架构丰富': None,
    '触控': None,
    '政治性': 'https://store.steampowered.com/search/?&tags=4853&snr=1_241_4_political',
    '迷幻': None,
    '时间管理': None,
    '重制': 'https://store.steampowered.com/search/?&tags=5708&snr=1_241_4_remake',
    '类魂系列': 'https://store.steampowered.com/search/?&tags=29482&snr=1_241_4_soulslike',
    '情感': None,
    '模组': 'https://store.steampowered.com/search/?&tags=5348&snr=1_241_4_mod',
    '4X': 'https://store.steampowered.com/search/?&tags=1670&snr=1_241_4_x',
    '合作战役': None,
    '3D视觉': None,
    '龙': 'https://store.steampowered.com/search/?&tags=4046&snr=1_241_4_dragons',
    '剑术': 'https://store.steampowered.com/search/?&tags=4608&snr=1_241_4_swordplay',
    '电竞': 'https://store.steampowered.com/search/?&tags=5055&snr=1_241_4_esports',
    '海盗': 'https://store.steampowered.com/search/?&tags=1681&snr=1_241_4_pirates', '体验': None,
    '奔跑': None,
    '角色动作': None,
    '冷战': None,
    '忍者': 'https://store.steampowered.com/search/?&tags=1688&snr=1_241_4_ninja',
    '体素': 'https://store.steampowered.com/search/?&tags=1732&snr=1_241_4_voxel', '少女游戏': None,
    '灵异': None,
    '恐龙': None,
    '政治': 'https://store.steampowered.com/search/?&tags=4754&snr=1_241_4_politics',
    '龙与地下城': None,
    '教程': None,
    '漫画': 'https://store.steampowered.com/search/?&tags=1751&snr=1_241_4_comicbook',
    '2D 平台': None,
    '物品管理': None,
    '电脑角色扮演': 'https://store.steampowered.com/search/?&tags=4474&snr=1_241_4_crpg',
    '游戏工坊': 'https://store.steampowered.com/search/?&tags=5310&snr=1_241_4_gamesworkshop',
    '黑客': None,
    '交易卡牌': 'https://store.steampowered.com/search/?&tags=9271&snr=1_241_4_tradingcardgame',
    '现代': None,
    '过场动画': None,
    '自制枪械': None,
    '讽刺': None,
    '创世神': 'https://store.steampowered.com/search/?&tags=5300&snr=1_241_4_godgame',
    '众筹': None,
    '自然': None,
    '黑色': None,
    '西部': 'https://store.steampowered.com/search/?&tags=1647&snr=1_241_4_western',
    '谐仿': None,
    '非线性': None,
    '开放世界生存制作': 'https://store.steampowered.com/search/?&tags=1100689&snr=1_241_4_openworldsurvivalcraft',
    '哲理': None,
    '无声主角': None,
    '网格导向动作': None,
    '小游戏': None,
    '暗杀': 'https://store.steampowered.com/search/?&tags=4376&snr=1_241_4_assassin',
    '农业': 'https://store.steampowered.com/search/?&tags=22602&snr=1_241_4_agriculture',
    'TrackIR': None,
    '子弹时间': 'https://store.steampowered.com/search/?&tags=5796&snr=1_241_4_bullettime',
    '猫': None,
    '时空旅行': 'https://store.steampowered.com/search/?&tags=10679&snr=1_241_4_timetravel',
    '神话': None,
    '游戏相关': None,
    '哥特': 'https://store.steampowered.com/search/?&tags=3952&snr=1_241_4_gothic',
    '限时': None,
    '恶人主角': 'https://store.steampowered.com/search/?&tags=11333&snr=1_241_4_villainprotagonist',
    '狩猎': None, '美国': 'https://store.steampowered.com/search/?&tags=13190&snr=1_241_4_america',
    '牌组构建': 'https://store.steampowered.com/search/?&tags=32322&snr=1_241_4_deckbuilding',
    '狗': None, '水底': 'https://store.steampowered.com/search/?&tags=9157&snr=1_241_4_underwater',
    '全动态影像': None,
    '职业导向': None,
    '足球/美式足球': None,
    '桌上游戏': 'https://store.steampowered.com/search/?&tags=17389&snr=1_241_4_tabletop',
    '劫掠': None, '贸易': 'https://store.steampowered.com/search/?&tags=4202&snr=1_241_4_trading',
    '武术': 'https://store.steampowered.com/search/?&tags=6915&snr=1_241_4_martialarts',
    '快速反应事件': None,
    '钓鱼': 'https://store.steampowered.com/search/?&tags=15564&snr=1_241_4_fishing', '足球': None,
    '吸血鬼': None,
    '一战': None,
    '推理调查': None,
    '唯美格斗': None,
    '编程': 'https://store.steampowered.com/search/?&tags=5432&snr=1_241_4_programming',
    '时空操控': None,
    '小说改编': None,
    '殖民模拟': 'https://store.steampowered.com/search/?&tags=220585&snr=1_241_4_colonysim',
    '采矿': None,
    '阴谋': None,
    '资本主义': None,
    '沉浸式模拟': None,
    '人工智能': None,
    '异步多人': None,
    '农场模拟': 'https://store.steampowered.com/search/?&tags=87918&snr=1_241_4_farmingsim',
    '续作': None,
    '不可思议迷宫': None,
    '音乐动态生成': None,
    '信仰': None,
    '海战': 'https://store.steampowered.com/search/?&tags=4994&snr=1_241_4_navalcombat',
    '动态记叙': None,
    '360 视频': None,
    '棋类': None,
    '马匹': None,
    '越野': None,
    '战锤40K': 'https://store.steampowered.com/search/?&tags=12286&snr=1_241_4_warhammer40k',
    '帆船': None,
    '政治模拟': 'https://store.steampowered.com/search/?&tags=26921&snr=1_241_4_politicalsim',
    '乐高': 'https://store.steampowered.com/search/?&tags=1736&snr=1_241_4_lego', '低容错': None,
    '精确平台': None,
    '六自由度': None,
    '外交': None,
    '弹球': None,
    '火星': None,
    '星球大战': 'https://store.steampowered.com/search/?&tags=1735&snr=1_241_4_starwars', '赌博': None,
    '益智问答': None,
    '交谈': None,
    '轨道射击': None,
    '打字': None,
    '战斗': None,
    '推箱子': None,
    '生活模拟': None,
    '地底': None,
    'Steam 主机': None,
    '蓄意操控困难': None,
    '狼人': None,
    '高尔夫球': None,
    '传统类 Rogue': None,
    '摩托车': None,
    '纸牌': None,
    '自动化': 'https://store.steampowered.com/search/?&tags=255534&snr=1_241_4_automation',
    '标杆测试': None,
    '篮球': None,
    '蝙蝠侠': None,
    '车辆作战': None,
    '迷你高尔夫': None,
    '超人类主义': None,
    '单车': None,
    '硬件': None,
    '3D 格斗': None,
    '战斗竞速': None,
    '懒人游戏': 'https://store.steampowered.com/search/?&tags=615955&snr=1_241_4_idler',
    '长片电影': None,
    '拳击': None,
    '摔角': None,
    '潜水艇': None,
    '英雄射击': None,
    '医疗模拟': None,
    '交通运输': None,
    '雪': None,
    '射箭': None,
    '棒球': None,
    '台球': None,
    '骑车': None,
    '刷宝射击游戏': None,
    '网球': None,
    '保龄球': None,
    '非对称 VR': None,
    '喷气机': None,
    'Rogue 恶魔城': None,
    '冰球': None,
    '劳拉·克劳馥': None,
    '摩托车越野': None,
    '收集马拉松': None,
    '旅鼠': None,
    '拼字': None,
    '疫病爆发模拟': None,
    '滑行': None,
    '情境': None,
    '社交推理': None,
    '单板滑雪': None,
    '滑雪': None,
    '自行车越野': None,
    '电子音乐': None,
    '自走棋': None,
    '器乐': None,
    'ATV': None,
    '电子': None,
    '摇滚乐': None,
    '末日': 'https://store.steampowered.com/search/?&tags=3835&snr=1_241_4_postapocalyptic',
    '程序生成': 'https://store.steampowered.com/search/?&tags=5125&snr=1_241_4_proceduralgeneration',
    '团队导向': 'https://store.steampowered.com/search/?&tags=5711&snr=1_241_4_teambased',
    '超級英雄': 'https://store.steampowered.com/search/?&tags=1671&snr=1_241_4_superhero',
    '海军': 'https://store.steampowered.com/search/?&tags=6910&snr=1_241_4_naval',
    '六角格棋盘': 'https://store.steampowered.com/search/?&tags=1717&snr=1_241_4_hexgrid',
    '卡牌战斗': 'https://store.steampowered.com/search/?&tags=791774&snr=1_241_4_cardbattler',
    '狙击手': None,
    '罗马': None,
    '外国': None,
    '滑板': None,
    '声控': None
}
